# Generated by Django 5.1.7 on 2025-04-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_time', models.CharField(choices=[('15min', '15 minutes'), ('30min', '30 minutes'), ('1hour', '1 hour')], max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=5, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_time', models.CharField(choices=[('15min', '15 minutes'), ('30min', '30 minutes'), ('1hour', '1 hour')], max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('last_actual_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('last_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('predicted_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('tp1', models.DecimalField(decimal_places=5, max_digits=20)),
                ('tp2', models.DecimalField(decimal_places=5, max_digits=20)),
                ('sl', models.DecimalField(decimal_places=5, max_digits=20)),
                ('confidence_interval', models.CharField(max_length=50)),
                ('confidence_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
